# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5628f9d0960f52f3a24d64989d58ea2231716eb49e043681a5b02bd4fd519237bb5ea9d885c6d644925ac133198541d5ad4f66a5d705954f64b22e72defca6de

test:
  secret_key_base: 5f776b0cebd264ebc73872ced88c975360c668dd4d1805fb393aff521def56a34efd063c42742a1b4074fe7d5e7f77aa0793d27fe0f654dabc73e6c373878f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
